version: '3'

services:

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks: 
      - desafio-network
    ports: 
      - "8080:80"
    depends_on: 
      - app
 
  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s  node server.js
    networks: 
      - desafio-network
    tty: true
    depends_on: 
      - db  

  db:
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./mysqlInit/init.sql:/data/application/init.sql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafio-network


networks: 
  desafio-network:
    driver: bridge